[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 26, columns 3--9) property name \u001B[34mformat\u001B[39m is invalid\n26: \u001B[34m  format:\u001B[39m\n     ~~~~~~~\n27: \u001B[34m    pdf:\u001B[39m\n\u001B[34mâ„¹\u001B[39m The error happened in location \u001B[34mbook\u001B[39m:\u001B[34mformat\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m42120\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82871\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82723\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m90654\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
